import * as THREE from 'three';
import type { BoardArray, Piece, RotationStateId, TypeId } from '@engine/types';
import { hasCollision } from '@engine/core/collision';
import { unpackCells } from '@engine/pieces/rotations';
import type { CellTuple } from '@engine/pieces/definitions';
import { findRotationState } from './rotation-state';
import { GHOST_DASH } from './constants';
import { boardToRenderVec3, depthScale } from './coords';

const CELL_EDGES = [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]] as const;
const CORNERS = [[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]] as const;
type Edge = { cell: CellTuple; a: readonly [number, number, number]; b: readonly [number, number, number] };
const collisionAnchor: [number, number, number] = [0, 0, 0]; const center = new THREE.Vector3();
function bakeGeometry(mesh: THREE.LineSegments, ax: number, ay: number, az: number): void { const edges = mesh.userData['edges'] as readonly Edge[]; const position = mesh.geometry.getAttribute('position') as THREE.BufferAttribute; let offset = 0; for (const edge of edges) { const [cx, cy, cz] = edge.cell; const bz = az + cz; boardToRenderVec3(center, ax + cx, ay + cy, bz); const scale = depthScale(bz); for (const corner of [edge.a, edge.b]) { position.setXYZ(offset, center.x + corner[0] * scale, center.y - corner[2], center.z + corner[1] * scale); offset += 1; } } position.needsUpdate = true; }
export function createGhostMesh(typeId: TypeId, rotationStateId: RotationStateId): THREE.LineSegments { const cells = unpackCells(findRotationState(typeId, rotationStateId)); const edges: Edge[] = []; const seen = new Set<string>(); for (const cell of cells) for (const [aIndex, bIndex] of CELL_EDGES) { const a = CORNERS[aIndex]; const b = CORNERS[bIndex]; const absoluteA = [cell[0] + a[0], cell[1] + a[1], cell[2] + a[2]]; const absoluteB = [cell[0] + b[0], cell[1] + b[1], cell[2] + b[2]]; const key = [absoluteA.join(','), absoluteB.join(',')].sort().join('|'); if (seen.has(key)) continue; seen.add(key); edges.push({ cell, a, b }); } const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.Float32BufferAttribute(edges.length * 6, 3)); const material = new THREE.LineDashedMaterial({ color: 0xffffff, dashSize: GHOST_DASH[0], gapSize: GHOST_DASH[1], transparent: true, opacity: 0.72, depthTest: true, depthWrite: false }); const mesh = new THREE.LineSegments(geometry, material); mesh.renderOrder = 2; mesh.userData['typeId'] = typeId; mesh.userData['rotationStateId'] = rotationStateId; mesh.userData['cells'] = cells; mesh.userData['edges'] = edges; bakeGeometry(mesh, 0, 0, 0); mesh.computeLineDistances(); return mesh; }
export function updateGhostTransform(mesh: THREE.LineSegments, activePiece: Pick<Piece, 'anchor' | 'typeId' | 'rotationStateId'>, board: BoardArray): void { if (mesh.userData['typeId'] !== activePiece.typeId || mesh.userData['rotationStateId'] !== activePiece.rotationStateId) throw new Error('ghost geometry does not match active piece'); const cells = mesh.userData['cells'] as readonly CellTuple[]; collisionAnchor[0] = activePiece.anchor[0]!; collisionAnchor[1] = activePiece.anchor[1]!; collisionAnchor[2] = activePiece.anchor[2]!; let remaining = 20; while (remaining > 0) { collisionAnchor[2] -= 1; if (hasCollision(board, cells, collisionAnchor, activePiece.typeId)) { collisionAnchor[2] += 1; break; } remaining -= 1; } mesh.position.set(0, 0, 0); mesh.scale.set(1, 1, 1); bakeGeometry(mesh, collisionAnchor[0], collisionAnchor[1], collisionAnchor[2]); }
